import Zerror from '@0devs/error';

/**
 * config error class with codes
 */
class ConfigError extends Zerror {}

ConfigError.setCodes({
  INVALID_LOGGER: 'INVALID_LOGGER',
  INVALID_VALIDATION_FUNCTION: 'INVALID_VALIDATION_FUNCTION',
  INVALID_ARGS: 'INVALID_ARGS',
  INVALID_DATA: 'INVALID_DATA',
  INVALID_PLUGIN: 'INVALID_PLUGIN',
  INVALID_PLUGIN_TYPE: 'INVALID_PLUGIN_TYPE',
  INVALID_PLUGIN_READ: 'INVALID_PLUGIN_READ',
  IMMUTABLE: 'IMMUTABLE',
  UNKNOWN_SOURCE_TYPE: 'UNKNOWN_SOURCE_TYPE',
  FAILED_TO_READ_SOURCE: 'FAILED_TO_READ_SOURCE',
});

export default ConfigError;
